/* Auto-generated by gen_hashes.py — do not edit. */
#ifndef HASH_DEFS_H
#define HASH_DEFS_H

#define HASH_WEBIO 0xcf833a3178f36987ULL  /* webio.dll */
#define HASH_COMBASE 0x2627bbedf50a3f57ULL  /* combase.dll */
#define HASH_NTDLL 0xc4d165aebd972e9bULL  /* ntdll.dll */
#define HASH_WEBSOCKET_BEGIN 0x7bdca0c7ed8b8219ULL  /* WebSocketBeginClientHandshake */
#define HASH_COUNINIT 0xd5855f0bd5d0e86eULL  /* CoUninitialize */
#define HASH_RTLADD 0x51e6b95566324fb2ULL  /* RtlAddFunctionTable */

#endif /* HASH_DEFS_H */
